/* Pathway to B1 — Static Curriculum Data */
/* eslint-disable */
const CURRICULUM = {
  "a1-greet": {
    title: "Greetings & Introductions",
    icon: "👋", level: "A1",
    theory: [
      {
        heading: "Formal and Informal Greetings",
        body: "English greetings depend on the situation. Use <strong>Hello</strong>, <strong>Good morning</strong>, <strong>Good afternoon</strong>, or <strong>Good evening</strong> in formal situations — with strangers, at work, or when meeting someone for the first time. Use <strong>Hi</strong> or <strong>Hey</strong> with friends and family. <em>Good morning</em> is used before midday; <em>Good afternoon</em> from noon to around 6 pm; <em>Good evening</em> after that.",
      },
      {
        heading: "Introducing Yourself",
        body: "To introduce yourself say: <strong>My name is [name]</strong> or <strong>I'm [name]</strong>. You can add where you are from: <strong>I'm from Denmark / London / Spain</strong>. To ask someone's name say: <strong>What's your name?</strong> or <strong>What is your name, please?</strong> To ask where someone is from: <strong>Where are you from?</strong> To ask age: <strong>How old are you? — I'm twenty-five years old.</strong>",
      },
      {
        heading: "Useful Phrases for First Meetings",
        body: "When you meet someone for the first time say <strong>Nice to meet you</strong> or <strong>Pleased to meet you</strong>. The other person replies: <strong>Nice to meet you too!</strong> To say goodbye: <strong>Goodbye</strong> (formal), <strong>Bye</strong> (informal), <strong>See you later / See you tomorrow</strong>, or <strong>Take care</strong>. Always use <strong>please</strong> to be polite when making requests and <strong>thank you</strong> / <strong>thanks</strong> to show gratitude.",
      },
    ],
    examples: [
      { en: "Hello! My name is Sarah. Nice to meet you.", da: "Hej! Mit navn er Sarah. Dejligt at møde dig." },
      { en: "Good morning, Mr Jensen. How are you today?", da: "Godmorgen, hr. Jensen. Hvordan har du det i dag?" },
      { en: "Hi! I'm Tom. I'm from London.", da: "Hej! Jeg er Tom. Jeg er fra London." },
      { en: "What's your name? — My name is Anna.", da: "Hvad hedder du? — Mit navn er Anna." },
      { en: "Where are you from? — I'm from Denmark.", da: "Hvor er du fra? — Jeg er fra Danmark." },
      { en: "How old are you? — I'm twenty-five years old.", da: "Hvor gammel er du? — Jeg er femogtyve år gammel." },
      { en: "This is my colleague, Maria. Pleased to meet you!", da: "Dette er min kollega, Maria. Dejligt at møde dig!" },
      { en: "Goodbye! See you tomorrow!", da: "Farvel! Vi ses i morgen!" },
    ],
    flashcards: [
      { front: "Hello", back: "Hej" },
      { front: "Goodbye", back: "Farvel" },
      { front: "Good morning", back: "Godmorgen" },
      { front: "Good evening", back: "Godaften" },
      { front: "What's your name?", back: "Hvad hedder du?" },
      { front: "My name is…", back: "Mit navn er…" },
      { front: "Nice to meet you", back: "Dejligt at møde dig" },
      { front: "Where are you from?", back: "Hvor er du fra?" },
      { front: "Thank you", back: "Tak" },
      { front: "Please", back: "Vær så venlig / tak" },
    ],
    quiz: [
      { q: "Which greeting is most appropriate in a formal work situation?", options: ["Hey!", "Good morning!", "Yo!", "What's up?"], correct: 1, explain: "'Good morning' is the formal greeting. 'Hey', 'Yo', and 'What's up?' are informal." },
      { q: "Complete the sentence: 'My ___ is John.'", options: ["call", "named", "name", "am"], correct: 2, explain: "We say 'My name is John.' This is the standard way to introduce yourself." },
      { q: "'Nice to meet you' is said when you:", options: ["say goodbye to a friend", "meet someone for the first time", "answer the phone", "order food"], correct: 1, explain: "'Nice to meet you' is a greeting for first meetings." },
      { q: "How do you ask someone their name?", options: ["What name you?", "What's your name?", "How your name?", "Who name?"], correct: 1, explain: "'What's your name?' is the correct question. The others are not grammatical English." },
      { q: "Which phrase means 'I am happy to meet you'?", options: ["See you later!", "Take care!", "Pleased to meet you!", "How are you?"], correct: 2, explain: "'Pleased to meet you' expresses happiness at meeting someone for the first time." },
    ],
  },
  "a1-num": {
    title: "Numbers, Days & Time",
    icon: "🕒", level: "A1",
    theory: [
      {
        heading: "Cardinal Numbers",
        body: "Learn numbers <strong>1–20</strong> first: one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty. Then the tens: <strong>twenty, thirty, forty, fifty, sixty, seventy, eighty, ninety, one hundred</strong>. For numbers like 21, combine them: <strong>twenty-one</strong> (always use a hyphen in writing: twenty-one, thirty-five, etc.).",
      },
      {
        heading: "Days of the Week",
        body: "The seven days are: <strong>Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday</strong>. In the UK the week starts on Monday. <strong>Weekend</strong> = Saturday and Sunday. <strong>Weekday</strong> = Monday to Friday. Use <em>on</em> with days: <strong>on Monday</strong>, <strong>on Fridays</strong> (= every Friday). Capital letters are always used for days of the week in English.",
      },
      {
        heading: "Telling the Time",
        body: "For exact hours say: <strong>It's three o'clock.</strong> For 30 minutes past: <strong>It's half past three.</strong> For 15 minutes past: <strong>It's quarter past three.</strong> For 15 minutes before the hour: <strong>It's quarter to four.</strong> For other minutes: <strong>It's ten past three / It's twenty to four.</strong> In formal writing you can use the 24-hour clock: 14:30. Always ask: <strong>What time is it?</strong> or <strong>What's the time?</strong>",
      },
    ],
    examples: [
      { en: "It is three o'clock. The shop opens at nine.", da: "Klokken er tre. Butikken åbner klokken ni." },
      { en: "Today is Monday. Tomorrow is Tuesday.", da: "I dag er mandag. I morgen er tirsdag." },
      { en: "There are seven days in a week.", da: "Der er syv dage i en uge." },
      { en: "I wake up at half past seven every morning.", da: "Jeg vågner op klokken halv otte hver morgen." },
      { en: "The meeting is on Friday at quarter to ten.", da: "Mødet er fredag klokken kvart i ti." },
      { en: "My birthday is on the fifteenth of June.", da: "Min fødselsdag er den femtende juni." },
      { en: "One hundred students study English here.", da: "Hundrede studerende studerer engelsk her." },
      { en: "It is twenty-five past two in the afternoon.", da: "Klokken er fem i halv tre om eftermiddagen." },
    ],
    flashcards: [
      { front: "What time is it?", back: "Hvad er klokken?" },
      { front: "Half past three", back: "Halv fire (kl. 3:30)" },
      { front: "Quarter past", back: "Kvart over" },
      { front: "Quarter to", back: "Kvart i" },
      { front: "Monday", back: "Mandag" },
      { front: "Wednesday", back: "Onsdag" },
      { front: "Friday", back: "Fredag" },
      { front: "Weekend", back: "Weekend (lørdag + søndag)" },
      { front: "Twenty-one", back: "Enogtyve" },
      { front: "One hundred", back: "Hundrede" },
    ],
    quiz: [
      { q: "How do you write the number 35 in words?", options: ["thirty five", "thirty-five", "thirtyfive", "five-thirty"], correct: 1, explain: "Numbers between 21 and 99 are written with a hyphen: thirty-five." },
      { q: "'Half past three' means:", options: ["3:00", "3:15", "3:30", "3:45"], correct: 2, explain: "'Half past three' = 3:30. The minute hand is halfway past the hour." },
      { q: "Which day comes after Wednesday?", options: ["Monday", "Tuesday", "Thursday", "Friday"], correct: 2, explain: "The order is Mon, Tue, Wed, Thu, Fri, Sat, Sun." },
      { q: "'Quarter to four' means:", options: ["4:15", "3:45", "4:45", "3:15"], correct: 1, explain: "'Quarter to four' = 15 minutes before 4 o'clock = 3:45." },
      { q: "How do you ask for the time politely?", options: ["What time?", "Time please!", "What time is it, please?", "Clock now?"], correct: 2, explain: "'What time is it, please?' is the polite, grammatically correct way to ask." },
    ],
  },
  "a1-fam": {
    title: "Family & People",
    icon: "👨‍👩‍👧", level: "A1",
    theory: [
      {
        heading: "Family Members",
        body: "Core family vocabulary: <strong>mother / mum / mom</strong> (informal), <strong>father / dad</strong> (informal), <strong>brother, sister, grandmother / grandma, grandfather / grandpa, aunt, uncle, cousin, son, daughter, husband, wife</strong>. Collective words: <strong>parents</strong> (mother + father), <strong>children</strong> (plural of child), <strong>grandparents, siblings</strong> (brothers and sisters). Extended family: <strong>niece</strong> (brother's/sister's daughter), <strong>nephew</strong> (brother's/sister's son).",
      },
      {
        heading: "Describing People with 'Have' and 'Be'",
        body: "Use <strong>have</strong> to describe physical features: <strong>She has brown hair. He has blue eyes. They have two children.</strong> Use <strong>be</strong> for age, size, and character: <strong>She is tall. He is young. She is kind.</strong> Useful adjectives: <em>tall, short, young, old, kind, funny, quiet, loud, clever, friendly</em>.",
      },
      {
        heading: "Possessives",
        body: "To show belonging, add <strong>'s</strong> to a name: <strong>Anna's brother, Tom's mother.</strong> Use possessive pronouns: <strong>my, your, his, her, its, our, their.</strong> Examples: <em>My parents are from Sweden. Her grandfather is 80. Their children go to school here.</em> Note: do NOT add an apostrophe to possessive pronouns — write <em>its</em>, not <em>it's</em> (which means 'it is').",
      },
    ],
    examples: [
      { en: "I have one brother and two sisters.", da: "Jeg har en bror og to søstre." },
      { en: "My mother is a teacher. She has brown hair.", da: "Min mor er lærer. Hun har brunt hår." },
      { en: "Her grandfather is eighty years old.", da: "Hendes bedstefar er irs år gammel." },
      { en: "We have three children: two sons and one daughter.", da: "Vi har tre børn: to sønner og en datter." },
      { en: "This is my wife, Julia. She is from Spain.", da: "Dette er min hustru, Julia. Hun er fra Spanien." },
      { en: "My parents live in a small town near Copenhagen.", da: "Mine forældre bor i en lille by nær København." },
      { en: "He has a cousin in Australia.", da: "Han har en fætter i Australien." },
      { en: "Our aunt and uncle visit us every Christmas.", da: "Vores faster og onkel besøger os hver jul." },
    ],
    flashcards: [
      { front: "Mother", back: "Mor" },
      { front: "Father", back: "Far" },
      { front: "Brother", back: "Bror" },
      { front: "Sister", back: "Søster" },
      { front: "Grandmother", back: "Mormor / Farmor" },
      { front: "Son", back: "Søn" },
      { front: "Daughter", back: "Datter" },
      { front: "Husband", back: "Mand / Ægtemand" },
      { front: "Wife", back: "Kone / Hustru" },
      { front: "Niece", back: "Niece" },
    ],
    quiz: [
      { q: "'She has blue eyes.' What does 'has' describe here?", options: ["an action", "a physical feature", "a possession", "a feeling"], correct: 1, explain: "'Have' is used to describe physical features like eye colour and hair." },
      { q: "Your mother's mother is your:", options: ["aunt", "cousin", "niece", "grandmother"], correct: 3, explain: "Your mother's mother is your grandmother." },
      { q: "Complete: '___ parents are from Denmark.' (talking about them)", options: ["They", "Their", "There", "Them"], correct: 1, explain: "'Their' is the possessive pronoun for 'they'. 'They' is a subject pronoun." },
      { q: "'I have two ___.' (more than one child)", options: ["childs", "childrens", "children", "child"], correct: 2, explain: "'Child' has an irregular plural: children. Never 'childs' or 'childrens'." },
      { q: "Your brother's daughter is your:", options: ["cousin", "niece", "sister", "aunt"], correct: 1, explain: "Your brother's or sister's daughter is your niece." },
    ],
  },
  "a1-food": {
    title: "Food & Drink",
    icon: "🍞", level: "A1",
    theory: [
      {
        heading: "Common Food and Drink Vocabulary",
        body: "Key food words: <strong>bread, butter, milk, cheese, eggs, meat, chicken, fish, vegetables, fruit, rice, pasta, soup, salad, cake.</strong> Drinks: <strong>water, coffee, tea, juice, beer, wine, lemonade.</strong> Meals: <strong>breakfast</strong> (morning), <strong>lunch</strong> (midday), <strong>dinner / supper</strong> (evening). <em>Snack</em> = a small amount of food between meals.",
      },
      {
        heading: "Ordering Food Politely",
        body: "In a café or restaurant use these polite phrases: <strong>I would like… / I'd like…</strong> (most polite), <strong>Can I have…?</strong> (common), <strong>Could I have…?</strong> (very polite). Examples: <em>I'd like a coffee with milk, please. Could I have the menu? Can I have some water?</em> Always add <strong>please</strong> at the end. To get the bill: <strong>Could I have the bill, please?</strong>",
      },
      {
        heading: "Countable and Uncountable Nouns",
        body: "Some food words are <strong>countable</strong> — they have a singular and plural form: <em>an apple / two apples, an egg / three eggs, a sandwich / two sandwiches.</em> Others are <strong>uncountable</strong> — they have no plural and cannot be used with <em>a/an</em>: <em>milk, bread, water, butter, rice.</em> With uncountable nouns use <strong>some</strong> (positive) or <strong>any</strong> (negative/question): <em>I'd like some milk. We don't have any bread. Do you have any coffee?</em>",
      },
    ],
    examples: [
      { en: "I would like a coffee with milk, please.", da: "Jeg vil gerne have en kaffe med mælk, tak." },
      { en: "Can I have some bread and butter, please?", da: "Kan jeg få noget brød og smør, tak?" },
      { en: "She eats an apple every day.", da: "Hun spiser et æble hver dag." },
      { en: "We need some milk and two eggs.", da: "Vi skal bruge noget mælk og to æg." },
      { en: "The pasta is very good in this restaurant.", da: "Pastaen er meget god på denne restaurant." },
      { en: "Would you like some more tea?", da: "Vil du have lidt mere te?" },
      { en: "I don't eat meat. I'm a vegetarian.", da: "Jeg spiser ikke kød. Jeg er vegetar." },
      { en: "Fish and chips is a traditional British dish.", da: "Fish and chips er en traditionel britisk ret." },
    ],
    flashcards: [
      { front: "Bread", back: "Brød" },
      { front: "Milk", back: "Mælk" },
      { front: "Coffee", back: "Kaffe" },
      { front: "Tea", back: "Te" },
      { front: "Egg", back: "Æg" },
      { front: "Chicken", back: "Kylling" },
      { front: "Vegetables", back: "Grøntsager" },
      { front: "I would like…", back: "Jeg vil gerne have…" },
      { front: "The bill, please", back: "Regningen, tak" },
      { front: "Some (uncountable)", back: "Noget (bruges med utælleligt substantiv)" },
    ],
    quiz: [
      { q: "Which noun is uncountable?", options: ["egg", "apple", "milk", "sandwich"], correct: 2, explain: "Milk is uncountable — you cannot say 'a milk' or 'two milks'. Use 'some milk'." },
      { q: "Complete: 'I'd like ___ coffee, please.'", options: ["a", "some", "an", "any"], correct: 0, explain: "Coffee is countable when you order one cup: 'a coffee'. Use 'some' for uncountable milk, water, etc." },
      { q: "'Can I have the menu?' — this person wants to:", options: ["pay the bill", "see what food is available", "order coffee", "leave the restaurant"], correct: 1, explain: "The menu lists all available food and drinks." },
      { q: "Which is the correct negative with an uncountable noun?", options: ["I don't have some bread.", "I don't have any bread.", "I don't have a bread.", "I don't have breads."], correct: 1, explain: "Use 'any' in negatives with uncountable nouns: 'I don't have any bread.'" },
      { q: "'Would you like some more?' — the speaker is:", options: ["asking for more food", "offering more food", "ordering food", "paying the bill"], correct: 1, explain: "'Would you like some more?' is an offer, not a request." },
    ],
  },
  "a1-day": {
    title: "Daily Routines",
    icon: "🌅", level: "A1",
    theory: [
      {
        heading: "Present Simple for Habits and Routines",
        body: "Use the <strong>present simple</strong> tense for things you do regularly — every day, every week, etc. <em>I wake up at 7. She goes to work by bus. He reads before bed.</em> The verb changes for <strong>he / she / it</strong>: add <strong>-s</strong> or <strong>-es</strong>. Rules: most verbs + <em>s</em>: <em>work → works, eat → eats.</em> Verbs ending in -ch, -sh, -ss, -x, -o + <em>es</em>: <em>watch → watches, go → goes.</em> Irregular: <em>have → has, be → is.</em>",
      },
      {
        heading: "Frequency Adverbs",
        body: "Frequency adverbs tell us HOW OFTEN something happens: <strong>always (100%), usually (≈80%), often (≈60%), sometimes (≈40%), rarely/seldom (≈10%), never (0%).</strong> Place them <strong>before the main verb</strong>: <em>I always eat breakfast. She never drinks coffee. He often goes to the gym.</em> Exception — place them <strong>after the verb 'be'</strong>: <em>He is always late. She is usually happy.</em>",
      },
      {
        heading: "Time Expressions for Routines",
        body: "Useful time expressions: <strong>every day / week / morning / evening / Monday.</strong> Use <strong>in</strong> with parts of the day: <em>in the morning, in the afternoon, in the evening.</em> Use <strong>at</strong> with night and clock times: <em>at night, at 8 o'clock.</em> Use <strong>on</strong> with days: <em>on Monday, on Fridays.</em> Use <strong>from…to</strong> for a period: <em>from nine to five.</em>",
      },
    ],
    examples: [
      { en: "I wake up at half past six every morning.", da: "Jeg vågner op klokken halv syv hver morgen." },
      { en: "She always has breakfast before work.", da: "Hun spiser altid morgenmad inden arbejde." },
      { en: "He goes to the gym three times a week.", da: "Han går i fitnesscenter tre gange om ugen." },
      { en: "We usually have dinner at seven o'clock.", da: "Vi spiser normalt middag klokken syv." },
      { en: "The children never go to bed late.", da: "Børnene går aldrig sent i seng." },
      { en: "She works in an office from nine to five.", da: "Hun arbejder på et kontor fra ni til fem." },
      { en: "Do you drink coffee in the morning?", da: "Drikker du kaffe om morgenen?" },
      { en: "He sometimes reads a book before going to sleep.", da: "Han læser sommetider en bog, inden han går i seng." },
    ],
    flashcards: [
      { front: "Wake up", back: "Vågne op" },
      { front: "Have breakfast", back: "Spise morgenmad" },
      { front: "Go to work", back: "Tage på arbejde" },
      { front: "Come home", back: "Komme hjem" },
      { front: "Have dinner", back: "Spise middag" },
      { front: "Go to bed", back: "Gå i seng" },
      { front: "Always", back: "Altid" },
      { front: "Sometimes", back: "Sommetider" },
      { front: "Never", back: "Aldrig" },
      { front: "Every day", back: "Hver dag" },
    ],
    quiz: [
      { q: "'She ___ to school by bus.' (daily habit)", options: ["go", "going", "goes", "is going"], correct: 2, explain: "Add -es to 'go' for he/she/it: she goes." },
      { q: "Where does the frequency adverb go? 'He ___ late for work.' (always)", options: ["He always is late", "He is always late", "Always he is late", "He is late always"], correct: 1, explain: "With the verb 'be', frequency adverbs come AFTER it: 'He is always late.'" },
      { q: "Which sentence is correct?", options: ["I sometimes goes running.", "She never eat meat.", "He usually works from home.", "They always is tired."], correct: 2, explain: "'He usually works from home' is correct. 'Goes' and 'eat' show wrong agreement; 'is' needs to come before 'always'." },
      { q: "Use the correct preposition: 'I go running ___ the morning.'", options: ["at", "on", "in", "by"], correct: 2, explain: "Use 'in' with parts of the day: in the morning, in the afternoon, in the evening." },
      { q: "Present simple third person: 'My father ___ the newspaper every morning.'", options: ["read", "reads", "reading", "is reading"], correct: 1, explain: "Third person singular (he/she/it) needs -s: reads." },
    ],
  },
  "a1-town": {
    title: "Places in Town & Prepositions",
    icon: "🏙️", level: "A1",
    theory: [
      {
        heading: "Places in Town",
        body: "Key places: <strong>bank, supermarket, post office, library, hospital, school, park, cinema, restaurant, hotel, bus stop, train station, pharmacy / chemist, police station, sports centre, town hall, museum, café.</strong> Note British English spellings: <em>chemist</em> (= pharmacy), <em>cinema</em> (= movie theater US), <em>car park</em> (= parking lot US).",
      },
      {
        heading: "Prepositions of Place",
        body: "Memorise these: <strong>next to</strong> (ved siden af) — the café is next to the bank. <strong>opposite</strong> (overfor) — the library is opposite the park. <strong>between</strong> (mellem) — the shop is between the bank and the café. <strong>in front of</strong> (foran) — the bus stop is in front of the cinema. <strong>behind</strong> (bag ved) — the car park is behind the hotel. <strong>near</strong> (nær) — the station is near the town centre. <strong>on the corner of</strong> (på hjørnet af).",
      },
      {
        heading: "Asking for and Giving Directions",
        body: "To ask: <strong>Excuse me, where is the bank?</strong> / <strong>How do I get to the station?</strong> / <strong>Is there a pharmacy near here?</strong> To give directions: <strong>Go straight on.</strong> <strong>Turn left / right</strong> (at the traffic lights / at the junction). <strong>Take the first / second left.</strong> <strong>It's on the left / right.</strong> <strong>It's about a five-minute walk.</strong>",
      },
    ],
    examples: [
      { en: "The supermarket is next to the train station.", da: "Supermarkedet er ved siden af togstationen." },
      { en: "The bank is opposite the post office.", da: "Banken er overfor posthuset." },
      { en: "Excuse me, is there a pharmacy near here?", da: "Undskyld, er der et apotek i nærheden?" },
      { en: "Go straight on and turn left at the traffic lights.", da: "Gå ligeud og drej til venstre ved lyskrydset." },
      { en: "The library is between the school and the park.", da: "Biblioteket er mellem skolen og parken." },
      { en: "The hotel is on the corner of High Street and Park Road.", da: "Hotellet er på hjørnet af High Street og Park Road." },
      { en: "The hospital is behind the supermarket.", da: "Hospitalet er bag ved supermarkedet." },
      { en: "The cinema is about a ten-minute walk from here.", da: "Biografen er ca. ti minutters gang herfra." },
    ],
    flashcards: [
      { front: "Supermarket", back: "Supermarked" },
      { front: "Post office", back: "Posthus" },
      { front: "Library", back: "Bibliotek" },
      { front: "Pharmacy / Chemist", back: "Apotek" },
      { front: "Next to", back: "Ved siden af" },
      { front: "Opposite", back: "Overfor" },
      { front: "Between", back: "Mellem" },
      { front: "Turn left", back: "Drej til venstre" },
      { front: "Go straight on", back: "Gå ligeud" },
      { front: "On the corner", back: "På hjørnet" },
    ],
    quiz: [
      { q: "'The café is ___ the bank and the pharmacy.' (in the middle)", options: ["next to", "opposite", "between", "behind"], correct: 2, explain: "'Between' is used when something is in the middle of two things." },
      { q: "'Excuse me, ___ is the post office?'", options: ["what", "who", "where", "how"], correct: 2, explain: "'Where' asks about location." },
      { q: "A place where you borrow books is a:", options: ["cinema", "pharmacy", "library", "bank"], correct: 2, explain: "A library is where you borrow books for free." },
      { q: "'The school is ___ the park.' (across the road from it)", options: ["behind", "opposite", "next to", "between"], correct: 1, explain: "'Opposite' means directly across from something." },
      { q: "To ask for directions you say:", options: ["Where go the station?", "Station where?", "Excuse me, how do I get to the station?", "Go to station how?"], correct: 2, explain: "'Excuse me, how do I get to…?' is the correct and polite way to ask for directions." },
    ],
  },

  "a2-past": {
    title: "Talking About the Past",
    icon: "⏪", level: "A2",
    theory: [
      {
        heading: "Past Simple: Regular Verbs",
        body: "Add <strong>-ed</strong> to form the past simple of regular verbs: <em>work → worked, watch → watched, play → played.</em> Spelling rules: verbs ending in <em>-e</em>, add <em>-d</em> only: <em>live → lived, dance → danced.</em> Verbs ending in short vowel + consonant, double the consonant: <em>stop → stopped, plan → planned.</em> Verbs ending in consonant + <em>-y</em>, change to <em>-ied</em>: <em>study → studied, carry → carried.</em>",
      },
      {
        heading: "Past Simple: Irregular Verbs",
        body: "Many common verbs are irregular — the past form must be memorised. Essential ones: <strong>go → went, come → came, see → saw, eat → ate, drink → drank, have → had, be → was/were, do → did, say → said, get → got, make → made, take → took, know → knew, think → thought, find → found, buy → bought, write → wrote, read → read (same spelling, different pronunciation), tell → told, give → gave, feel → felt.</strong>",
      },
      {
        heading: "Negatives and Questions in Past Simple",
        body: "For <strong>negatives</strong>: subject + <strong>didn't</strong> (did not) + infinitive. <em>I didn't go. She didn't eat. They didn't know.</em> For <strong>yes/no questions</strong>: <strong>Did</strong> + subject + infinitive? <em>Did you go? Did she eat? Did they know?</em> For <strong>wh-questions</strong>: question word + did + subject + infinitive? <em>Where did you go? What did she eat?</em> IMPORTANT: the main verb always stays in the infinitive (base form) — NEVER add -ed in questions or negatives.",
      },
    ],
    examples: [
      { en: "Yesterday I went to the cinema with my friends.", da: "I går gik jeg i biograf med mine venner." },
      { en: "She worked in a restaurant when she was younger.", da: "Hun arbejdede på en restaurant, da hun var yngre." },
      { en: "We didn't go to school last Monday — it was a holiday.", da: "Vi gik ikke i skole sidste mandag — det var en helligdag." },
      { en: "Did you see the football match last night?", da: "Så du fodboldkampen i aftes?" },
      { en: "He made a delicious cake for the party.", da: "Han lavede en lækker kage til festen." },
      { en: "I lived in London for three years.", da: "Jeg boede i London i tre år." },
      { en: "They didn't know the answer to the question.", da: "De vidste ikke svaret på spørgsmålet." },
      { en: "When did you arrive in Denmark?", da: "Hvornår ankom du til Danmark?" },
    ],
    flashcards: [
      { front: "go → went", back: "gå → gik" },
      { front: "come → came", back: "komme → kom" },
      { front: "see → saw", back: "se → så" },
      { front: "have → had", back: "have → havde" },
      { front: "be → was/were", back: "være → var" },
      { front: "make → made", back: "lave → lavede" },
      { front: "buy → bought", back: "købe → købte" },
      { front: "Yesterday", back: "I går" },
      { front: "Last week", back: "Sidste uge" },
      { front: "didn't + infinitive", back: "Negation i datid (nægtelse)" },
    ],
    quiz: [
      { q: "'She ___ to the market yesterday.'", options: ["go", "goes", "went", "gone"], correct: 2, explain: "'Went' is the irregular past simple of 'go'." },
      { q: "Which is the correct negative form?", options: ["I not watched the film.", "I didn't watched the film.", "I didn't watch the film.", "I don't watched the film."], correct: 2, explain: "Negative: didn't + base verb (no -ed). 'I didn't watch' is correct." },
      { q: "Question form: '___ you enjoy the trip?'", options: ["Do", "Did", "Have", "Was"], correct: 1, explain: "Past simple questions use 'did': Did you enjoy…?" },
      { q: "Spell the past simple of 'stop':", options: ["stoped", "stopped", "stopted", "stopt"], correct: 1, explain: "Short vowel + consonant → double the consonant: stop → stopped." },
      { q: "'We ___ at home all weekend.' (past of 'be', subject = we)", options: ["was", "were", "are", "be"], correct: 1, explain: "'Were' is the past of 'be' for I/we/you/they. 'Was' is for he/she/it." },
    ],
  },
  "a2-shop": {
    title: "Shopping & Money",
    icon: "🛒", level: "A2",
    theory: [
      {
        heading: "Shopping Vocabulary",
        body: "Essential words: <strong>price, cost, how much, receipt, change</strong> (money back), <strong>sale / on sale, discount, size</strong> (S/M/L/XL), <strong>try on</strong> (to put on clothes to see if they fit), <strong>fit</strong> (if clothes are the right size), <strong>checkout, till / cash register, cash, card payment, refund.</strong> British English: <em>till</em> = cash register, <em>shop</em> = store, <em>queue</em> = line (to wait in).",
      },
      {
        heading: "Asking About Price",
        body: "Key questions: <strong>How much is this?</strong> (singular) / <strong>How much are these?</strong> (plural) / <strong>How much does this cost?</strong> Answers: <em>It costs twelve pounds fifty. It's two pounds. They are three for five pounds.</em> Reading prices: £12.50 = twelve pounds fifty; £0.99 = ninety-nine pence / p. Note: <em>pence</em> is plural of <em>penny</em>.",
      },
      {
        heading: "Polite Requests in Shops",
        body: "To ask to try something: <strong>Can I try this on?</strong> To ask about sizes: <strong>Do you have this in a medium / larger / smaller size?</strong> To look for something: <strong>I'm looking for…</strong> To check availability: <strong>Do you have…?</strong> To pay: <strong>Could I pay by card?</strong> / <strong>Do you accept contactless?</strong> For a receipt: <strong>Could I have a receipt, please?</strong>",
      },
    ],
    examples: [
      { en: "How much does this jacket cost?", da: "Hvad koster denne jakke?" },
      { en: "It costs thirty-five pounds fifty.", da: "Den koster femogtredive pund og halvtreds pence." },
      { en: "Do you have this in a medium size?", da: "Har I det i mellemstor?" },
      { en: "Could I try these trousers on?", da: "Må jeg prøve disse bukser?" },
      { en: "I'm looking for a birthday present for my sister.", da: "Jeg leder efter en fødselsdagsgave til min søster." },
      { en: "There's a 20% discount on all shoes today.", da: "Der er 20% rabat på alle sko i dag." },
      { en: "Can I pay by card, or is it cash only?", da: "Kan jeg betale med kort, eller er det kun kontant?" },
      { en: "The receipt is in the bag.", da: "Kvitteringen er i posen." },
    ],
    flashcards: [
      { front: "How much is this?", back: "Hvad koster det?" },
      { front: "Discount", back: "Rabat" },
      { front: "Sale", back: "Udsalg" },
      { front: "Size (clothing)", back: "Størrelse" },
      { front: "Receipt", back: "Kvittering" },
      { front: "Change (money back)", back: "Byttepenge" },
      { front: "Try on", back: "Prøve (tøj)" },
      { front: "Refund", back: "Refundering / Pengene tilbage" },
      { front: "Cash", back: "Kontant" },
      { front: "I'm looking for…", back: "Jeg leder efter…" },
    ],
    quiz: [
      { q: "'How much ___ this jacket?' (asking the price of one item)", options: ["cost", "costs", "is", "does"], correct: 2, explain: "'How much is this?' is the most natural way. 'How much does this cost?' also works." },
      { q: "'Do you have this in a larger ___?'", options: ["price", "colour", "size", "model"], correct: 2, explain: "We ask for a different 'size' when clothes don't fit." },
      { q: "You want to pay without using cash. You:", options: ["ask for a receipt", "pay by card", "ask for a discount", "try it on"], correct: 1, explain: "Paying by card is the alternative to paying with cash." },
      { q: "20% off the original price means:", options: ["you pay 20% more", "you pay 20% less", "you get £20 back", "the item costs £20"], correct: 1, explain: "A 20% discount means the price is reduced by 20%." },
      { q: "'I'm looking for a blue dress.' This person:", options: ["has found a dress", "is selling a dress", "wants to buy a dress", "is describing their outfit"], correct: 2, explain: "'I'm looking for something' means you want to find or buy it." },
    ],
  },
  "a2-travel": {
    title: "Travel & Directions",
    icon: "🧭", level: "A2",
    theory: [
      {
        heading: "Transport and Travel Vocabulary",
        body: "Types of transport: <strong>bus, train, plane / flight, taxi / cab, underground / tube / metro, ferry, tram, car, bicycle / bike.</strong> Related places: <strong>airport, bus stop, train station, platform, terminal, port, harbour.</strong> Useful verbs: <em>catch a train/bus</em> (= get it in time), <em>miss a train/bus</em> (= be too late), <em>get on</em> (board), <em>get off</em> (leave), <em>change</em> (switch to another line/train).",
      },
      {
        heading: "Buying Tickets",
        body: "A <strong>single</strong> (or one-way) ticket = travel in one direction only. A <strong>return</strong> ticket = go and come back. <strong>First class</strong> = more comfortable, more expensive. <strong>Standard / second class</strong> = normal. Phrases: <em>A single to Edinburgh, please. Two returns to Oxford, please. Which platform does the train leave from? Is this seat taken? Does this train stop at Bath?</em>",
      },
      {
        heading: "Asking for and Giving Directions",
        body: "Asking: <strong>Excuse me, how do I get to…? / Is it far? / How long does it take?</strong> Giving directions: <strong>Take the number 5 bus.</strong> <strong>Get off at [stop name].</strong> <strong>It's about a ten-minute walk.</strong> <strong>Follow the signs for…</strong> <strong>You'll see it on your left/right.</strong> <strong>You can't miss it.</strong> (= it is easy to see)",
      },
    ],
    examples: [
      { en: "Could you tell me how to get to the airport?", da: "Kan du fortælle mig, hvordan jeg kommer til lufthavnen?" },
      { en: "A return ticket to Edinburgh, please.", da: "En returbillet til Edinburgh, tak." },
      { en: "Which platform does the train to London leave from?", da: "Hvilken perron afgår toget til London fra?" },
      { en: "Excuse me, is this the right bus for the city centre?", da: "Undskyld, er dette den rigtige bus til bycentret?" },
      { en: "How long does the journey take by train?", da: "Hvor lang tid tager rejsen med tog?" },
      { en: "Get off at the third stop and then turn right.", da: "Stå af ved den tredje stop, og drej derefter til højre." },
      { en: "The flight to Copenhagen departs at 14:35 from Gate B7.", da: "Flyet til København afgår kl. 14:35 fra gate B7." },
      { en: "I missed my bus and had to take a taxi.", da: "Jeg missede min bus og måtte tage en taxa." },
    ],
    flashcards: [
      { front: "Single ticket", back: "Enkeltbillet (én vej)" },
      { front: "Return ticket", back: "Returbillet (tur-retur)" },
      { front: "Platform", back: "Perron" },
      { front: "Departure", back: "Afgang" },
      { front: "Arrival", back: "Ankomst" },
      { front: "Get on", back: "Stige på (bus/tog)" },
      { front: "Get off", back: "Stå af (bus/tog)" },
      { front: "How long does it take?", back: "Hvor lang tid tager det?" },
      { front: "Is it far?", back: "Er det langt?" },
      { front: "Change (transport)", back: "Skifte (til anden linje)" },
    ],
    quiz: [
      { q: "A 'return ticket' means:", options: ["travel in one direction only", "travel there and back", "a refund on your ticket", "a business-class ticket"], correct: 1, explain: "A return ticket covers both the outward and return journey." },
      { q: "'Which ___ does the train leave from?'", options: ["door", "gate", "platform", "road"], correct: 2, explain: "Trains leave from platforms at a station." },
      { q: "'Get off at the next stop' means:", options: ["get on the next bus", "leave the bus at the next stop", "walk to the next stop", "run to catch the bus"], correct: 1, explain: "'Get off' means to leave a bus, train, or plane." },
      { q: "'I missed my train.' This means:", options: ["I caught the train in time", "I was too late for the train", "I found my train", "I enjoyed the train journey"], correct: 1, explain: "To 'miss' a bus or train means you arrived too late to catch it." },
      { q: "The opposite of 'departure' is:", options: ["terminal", "delay", "arrival", "boarding"], correct: 2, explain: "Departure = when something leaves; Arrival = when it gets there." },
    ],
  },
  "a2-health": {
    title: "Health & the Body",
    icon: "🩺", level: "A2",
    theory: [
      {
        heading: "Parts of the Body",
        body: "Head and face: <strong>head, forehead, eye(s), ear(s), nose, mouth, teeth (sing. tooth), cheek, chin, neck.</strong> Upper body: <strong>shoulder, arm, elbow, wrist, hand, finger, thumb, chest, back, stomach.</strong> Lower body: <strong>hip, leg, knee, ankle, foot (pl. feet), toe.</strong> Internal organs (common): <em>heart, lungs, brain, stomach.</em>",
      },
      {
        heading: "Describing Symptoms",
        body: "Common symptoms: <strong>I have a headache / stomachache / backache / toothache.</strong> <strong>I have a sore throat / sore eyes.</strong> <strong>I feel sick / nauseous.</strong> <strong>I have a cold / the flu / a fever / a cough / a rash.</strong> <strong>I've injured / hurt / twisted my ankle.</strong> <strong>I can't sleep.</strong> <strong>I feel dizzy / tired / weak.</strong> Note: <em>a cold</em> (noun) but <em>the flu</em> (with 'the').",
      },
      {
        heading: "At the Doctor's",
        body: "The doctor may ask: <strong>What's the matter? / What seems to be the problem? / Where does it hurt? / How long have you had this?</strong> You might answer: <strong>I've had it since yesterday / since Monday. It started three days ago. It hurts when I walk / breathe / swallow. I'm allergic to penicillin.</strong> The doctor might say: <strong>Take these tablets twice a day. Rest and drink plenty of fluids. Come back if it gets worse.</strong>",
      },
    ],
    examples: [
      { en: "I have a headache and a sore throat.", da: "Jeg har hovedpine og ondt i halsen." },
      { en: "My back has been hurting for three days.", da: "Min ryg har gjort ondt i tre dage." },
      { en: "She went to the doctor because she had a high fever.", da: "Hun gik til lægen, fordi hun havde høj feber." },
      { en: "I twisted my ankle while playing football.", da: "Jeg forstuvede min ankel, mens jeg spillede fodbold." },
      { en: "How long have you had this cough?", da: "Hvor længe har du haft denne hoste?" },
      { en: "I'm allergic to penicillin, so I need a different medicine.", da: "Jeg er allergisk over for penicillin, så jeg har brug for en anden medicin." },
      { en: "Take these tablets twice a day after meals.", da: "Tag disse tabletter to gange om dagen efter måltider." },
      { en: "I don't feel well. I think I have the flu.", da: "Jeg har det ikke godt. Jeg tror, jeg har influenza." },
    ],
    flashcards: [
      { front: "Headache", back: "Hovedpine" },
      { front: "Sore throat", back: "Ondt i halsen" },
      { front: "Fever", back: "Feber" },
      { front: "Cough", back: "Hoste" },
      { front: "Stomachache", back: "Mavepine" },
      { front: "I feel sick", back: "Jeg har det dårligt / Jeg er kvalm" },
      { front: "Allergic to", back: "Allergisk over for" },
      { front: "Tablet / Pill", back: "Tablet / Pille" },
      { front: "Twice a day", back: "To gange om dagen" },
      { front: "What's the matter?", back: "Hvad er der galt? / Hvad fejler du?" },
    ],
    quiz: [
      { q: "'I have a sore ___.' (it hurts to swallow)", options: ["head", "throat", "stomach", "back"], correct: 1, explain: "A sore throat is the symptom when it hurts to swallow." },
      { q: "'Where does it hurt?' — who typically asks this?", options: ["a shopkeeper", "a teacher", "a doctor", "a bus driver"], correct: 2, explain: "Doctors ask 'Where does it hurt?' to diagnose a patient." },
      { q: "'I've had a cold for three days.' The word 'for' shows:", options: ["the reason", "the duration", "the location", "the time of day"], correct: 1, explain: "'For' + a period of time shows how long something has been happening." },
      { q: "'Take these tablets twice a day' means:", options: ["take one tablet every two days", "take two tablets at once", "take one in the morning and one in the evening", "take two tablets twice a day"], correct: 2, explain: "Twice a day = two times a day, typically morning and evening." },
      { q: "If you are 'allergic to' something, it:", options: ["makes you better", "causes an unwanted physical reaction", "tastes good", "helps you sleep"], correct: 1, explain: "An allergy causes a negative physical reaction (rash, breathing problems, etc.)." },
    ],
  },
  "a2-work": {
    title: "Work & Jobs",
    icon: "💼", level: "A2",
    theory: [
      {
        heading: "Job Vocabulary",
        body: "Common jobs: <strong>teacher, doctor, nurse, engineer, lawyer, architect, journalist, chef / cook, driver, manager, receptionist, accountant, programmer / developer, salesperson, cleaner, plumber, electrician, designer, pilot, police officer.</strong> Sectors: <em>healthcare, education, IT, finance, retail, construction, media, hospitality.</em>",
      },
      {
        heading: "Talking About Work",
        body: "Asking about work: <strong>What do you do (for a living)?</strong> Answering: <strong>I work as a nurse. / I'm a teacher. / I work for Google. / I work in IT / finance / education.</strong> Other useful phrases: <strong>I'm self-employed</strong> (work for yourself), <strong>I'm freelance</strong> (not permanently employed), <strong>I'm unemployed / between jobs</strong>, <strong>I'm retired</strong>, <strong>I work part-time / full-time.</strong>",
      },
      {
        heading: "Workplace Phrases",
        body: "Common phrases: <strong>I have a meeting at ten.</strong> <strong>I'm on a deadline</strong> (= I must finish by a time). <strong>I work from home / remotely.</strong> <strong>I work shifts</strong> (= different hours each day). <strong>I got a promotion</strong> (= moved to a better/higher position). <strong>I applied for a job</strong> (= sent an application). <strong>I had an interview.</strong> <strong>I was offered the job / I got the job.</strong>",
      },
    ],
    examples: [
      { en: "What do you do for a living? — I work as a nurse.", da: "Hvad laver du? — Jeg arbejder som sygeplejerske." },
      { en: "She is an engineer at a large technology company.", da: "Hun er ingeniør i et stort teknologiselskab." },
      { en: "I work from home three days a week.", da: "Jeg arbejder hjemmefra tre dage om ugen." },
      { en: "He applied for a job as a teacher last month.", da: "Han søgte et job som lærer for en måned siden." },
      { en: "My sister is self-employed. She runs her own bakery.", da: "Min søster er selvstændig. Hun driver sit eget bageri." },
      { en: "I got a promotion last year and now I manage a team of ten people.", da: "Jeg fik en forfremmelse sidste år og leder nu et team på ti personer." },
      { en: "She works long hours as a doctor, often twelve hours a day.", da: "Hun arbejder lange timer som læge, ofte tolv timer om dagen." },
      { en: "I'm between jobs at the moment, but I have an interview tomorrow.", da: "Jeg er ledig for øjeblikket, men jeg har en jobsamtale i morgen." },
    ],
    flashcards: [
      { front: "I work as…", back: "Jeg arbejder som…" },
      { front: "I work for…", back: "Jeg arbejder for…" },
      { front: "Self-employed", back: "Selvstændig" },
      { front: "Promotion", back: "Forfremmelse" },
      { front: "Apply for a job", back: "Søge et job" },
      { front: "Interview", back: "Jobsamtale" },
      { front: "Full-time", back: "Fuldtid" },
      { front: "Part-time", back: "Deltid" },
      { front: "Deadline", back: "Deadline / Tidsfrist" },
      { front: "Work from home", back: "Arbejde hjemmefra" },
    ],
    quiz: [
      { q: "'I work ___ a nurse.'", options: ["like", "for", "as", "in"], correct: 2, explain: "'Work as' describes your role or job title." },
      { q: "'I'm self-employed' means:", options: ["you work for a big company", "you work for yourself", "you are unemployed", "you work part-time"], correct: 1, explain: "Self-employed people run their own business or work independently." },
      { q: "'I got a promotion' means:", options: ["I lost my job", "I got a new job somewhere else", "I moved to a higher position in my company", "I applied for a job"], correct: 2, explain: "A promotion is when you move to a better, higher position within the same company." },
      { q: "'What do you do for a living?' is asking about your:", options: ["hobbies", "family", "job", "hometown"], correct: 2, explain: "'What do you do for a living?' asks about your profession." },
      { q: "Which phrase means you must finish a task by a specific time?", options: ["I work shifts.", "I'm on a deadline.", "I work part-time.", "I got promoted."], correct: 1, explain: "'On a deadline' means you have a time limit to complete something." },
    ],
  },
  "a2-plans": {
    title: "Making Plans",
    icon: "📅", level: "A2",
    theory: [
      {
        heading: "Going To — for Plans Already Decided",
        body: "Use <strong>be going to + infinitive</strong> for plans and intentions you have already decided. <em>I'm going to visit my parents next weekend. She's going to start a new job in September. They're going to move to a bigger flat.</em> Structure: <strong>I am / He is / They are + going to + verb.</strong> Negatives: <em>I'm not going to go. She isn't going to come.</em>",
      },
      {
        heading: "Will — for Spontaneous Decisions and Predictions",
        body: "Use <strong>will + infinitive</strong> for decisions made at the moment of speaking (not pre-planned): <em>It's very hot. I'll open a window. Don't worry, I'll help you.</em> Also use <em>will</em> for predictions about the future (especially with think, probably, expect): <em>I think it will rain tomorrow. Prices will probably rise.</em> Structure: <strong>subject + will + infinitive.</strong> Contraction: <em>I'll, you'll, he'll, she'll, it'll, we'll, they'll.</em>",
      },
      {
        heading: "Present Continuous for Fixed Future Arrangements",
        body: "Use the <strong>present continuous (am/is/are + -ing)</strong> for fixed future arrangements — appointments, bookings, meetings that are already organised: <em>I'm meeting John on Tuesday. She's flying to Rome tomorrow. We're having dinner with the manager on Friday.</em> This is similar to 'going to' but emphasises the arrangement is confirmed. Time expressions for the future: <em>tomorrow, next week/month/year, in two weeks, soon, this weekend, on Saturday.</em>",
      },
    ],
    examples: [
      { en: "We are going to visit my parents next weekend.", da: "Vi skal besøge mine forældre næste weekend." },
      { en: "I'm going to start a new job in September.", da: "Jeg skal begynde i et nyt job i september." },
      { en: "It's very hot in here. I'll open a window.", da: "Det er meget varmt her. Jeg åbner et vindue." },
      { en: "Don't worry, I'll help you with the presentation.", da: "Bekymr dig ikke, jeg hjælper dig med præsentationen." },
      { en: "What are you going to do for your birthday?", da: "Hvad skal du lave til din fødselsdag?" },
      { en: "She's meeting her manager tomorrow at ten o'clock.", da: "Hun møder sin leder i morgen klokken ti." },
      { en: "I think it's going to be a difficult exam.", da: "Jeg tror, det bliver en svær eksamen." },
      { en: "Will you be at the party on Saturday?", da: "Er du til festen lørdag?" },
    ],
    flashcards: [
      { front: "I'm going to…", back: "Jeg skal… (planlagt hensigt)" },
      { front: "I will…", back: "Jeg vil… (spontan beslutning / forudsigelse)" },
      { front: "I'm meeting… (future)", back: "Jeg mødes med… (aftale)" },
      { front: "Next week", back: "Næste uge" },
      { front: "Tomorrow", back: "I morgen" },
      { front: "Soon", back: "Snart" },
      { front: "This weekend", back: "Denne weekend" },
      { front: "I think it will…", back: "Jeg tror, det vil…" },
      { front: "Plan / intention", back: "Plan / hensigt" },
      { front: "Arrangement", back: "Aftale / arrangement" },
    ],
    quiz: [
      { q: "'I ___ visit the dentist next Monday.' (already booked)", options: ["will", "am going to", "go to", "shall"], correct: 1, explain: "'Going to' is used for plans and decisions already made." },
      { q: "'The phone is ringing.' 'I ___ answer it.' (spontaneous)", options: ["am going to", "will", "am", "going"], correct: 1, explain: "'Will' is used for spontaneous decisions made at the moment of speaking." },
      { q: "'She ___ her friend at the airport at 6pm.' (confirmed arrangement)", options: ["meets", "is meeting", "will meet", "met"], correct: 1, explain: "Present continuous (is meeting) shows a confirmed, arranged future event." },
      { q: "Which shows a plan already decided before speaking?", options: ["I'll maybe go.", "I might go.", "I'm going to go.", "I could go."], correct: 2, explain: "'I'm going to go' shows a pre-planned intention." },
      { q: "'Don't worry, I ___ help you.' (spontaneous offer)", options: ["am going to", "will", "am", "going"], correct: 1, explain: "Spontaneous offers and decisions use 'will'." },
    ],
  },

  "b1-opinion": {
    title: "Giving Opinions & Agreeing",
    icon: "💬", level: "B1",
    theory: [
      {
        heading: "Phrases to Express Your Opinion",
        body: "Use these phrases to introduce a personal view (not a fact): <strong>In my opinion… / I think / believe / feel that… / As far as I'm concerned… / From my point of view… / It seems to me that… / Personally, I think…</strong> These signal that what follows is your perspective, not an objective truth. Using them makes your English sound more natural and polite, especially in discussions and essays.",
      },
      {
        heading: "Agreeing and Disagreeing Politely",
        body: "<strong>Agreeing:</strong> <em>I agree (with you). That's a good point. Absolutely. Exactly. I couldn't agree more. You're absolutely right. That's true.</em> <strong>Partly agreeing/disagreeing:</strong> <em>I see your point, but… / That's true, but… / I agree to some extent, but…</em> <strong>Disagreeing politely:</strong> <em>I'm not sure about that. / I disagree. / Actually, I think… / With respect, I think… / I see it differently.</em> Note: In English, direct contradiction is often softened.",
      },
      {
        heading: "Asking for Other People's Opinions",
        body: "To draw someone into a discussion: <strong>What do you think about…? / What's your view on…? / How do you feel about…? / Do you agree that…? / What's your opinion on…? / Would you say that…?</strong> In more formal discussions: <strong>What are your thoughts on this? / I'd be interested to hear your view.</strong> Asking for opinions makes conversations balanced and shows respect for others.",
      },
    ],
    examples: [
      { en: "In my opinion, learning a language takes patience and practice.", da: "Efter min mening kræver sprogtilegnelse tålmodighed og øvelse." },
      { en: "I think that social media has both advantages and disadvantages.", da: "Jeg mener, at sociale medier har både fordele og ulemper." },
      { en: "I see your point, but I think we need more evidence before deciding.", da: "Jeg forstår dit synspunkt, men jeg mener, vi har brug for mere bevis." },
      { en: "What's your view on working from home full-time?", da: "Hvad er din mening om at arbejde hjemmefra på fuld tid?" },
      { en: "I couldn't agree more — protecting the environment is our biggest challenge.", da: "Jeg er fuldstændig enig — miljøbeskyttelse er vores største udfordring." },
      { en: "As far as I'm concerned, the new plan needs much more thought.", da: "Hvad mig angår, har den nye plan brug for meget mere overvejelse." },
      { en: "That's an interesting perspective, but have you considered the costs?", da: "Det er et interessant synspunkt, men har du overvejet omkostningerne?" },
      { en: "Personally, I feel that we should invest more in public transport.", da: "Personligt mener jeg, at vi bør investere mere i offentlig transport." },
    ],
    flashcards: [
      { front: "In my opinion…", back: "Efter min mening…" },
      { front: "I think that…", back: "Jeg mener, at…" },
      { front: "I agree", back: "Jeg er enig" },
      { front: "I disagree", back: "Jeg er uenig" },
      { front: "That's a good point", back: "Det er et godt argument" },
      { front: "I see your point, but…", back: "Jeg forstår dit synspunkt, men…" },
      { front: "I couldn't agree more", back: "Jeg er fuldstændig enig" },
      { front: "What's your view on…?", back: "Hvad er din mening om…?" },
      { front: "From my point of view…", back: "Fra mit synspunkt…" },
      { front: "Personally, I feel that…", back: "Personligt mener jeg, at…" },
    ],
    quiz: [
      { q: "'In my opinion, this film is excellent.' The phrase 'In my opinion' signals:", options: ["an objective fact", "a personal view", "a question", "an order"], correct: 1, explain: "'In my opinion' introduces a personal view, not a fact." },
      { q: "'I ___ agree more — it's a great idea.' (expressing strong agreement)", options: ["could", "couldn't", "should", "wouldn't"], correct: 1, explain: "'I couldn't agree more' is an idiom meaning 'I agree completely'." },
      { q: "'I see your point, but…' is used when:", options: ["you fully agree", "you don't understand", "you partly disagree", "you change the subject"], correct: 2, explain: "This phrase acknowledges the other person's view while introducing a different one." },
      { q: "Which phrase ASKS for someone's opinion?", options: ["I think that…", "In my opinion…", "What's your view on…?", "I agree."], correct: 2, explain: "'What's your view on…?' is a question inviting someone to share their opinion." },
      { q: "'As far as I'm concerned' means:", options: ["I am worried about", "from my personal viewpoint", "I am sure that", "as long as"], correct: 1, explain: "'As far as I'm concerned' introduces a personal perspective or opinion." },
    ],
  },
  "b1-story": {
    title: "Telling Stories (Narrative Tenses)",
    icon: "📖", level: "B1",
    theory: [
      {
        heading: "Past Simple — Main Events",
        body: "The <strong>past simple</strong> tells the main events of a story in sequence. It moves the narrative forward. <em>She walked into the room. She saw a letter on the table. She picked it up and opened it.</em> Each event follows the last. This is the 'backbone' of storytelling. Use time linkers to connect events: <em>first, then, after that, next, finally, suddenly, immediately.</em>",
      },
      {
        heading: "Past Continuous — Background and Simultaneous Actions",
        body: "The <strong>past continuous</strong> (was/were + -ing) describes what was happening as background when the main events occurred. <em>It was raining when she arrived. Everyone was talking and laughing. The sun was shining over the city.</em> Also use it for two actions happening at the same time: <em>While she was cooking, he was reading.</em> The past continuous sets the scene — it does not move the story forward on its own.",
      },
      {
        heading: "Past Perfect — Events Before the Main Story",
        body: "The <strong>past perfect</strong> (had + past participle) shows that something happened <em>before</em> the main past events. <em>When he arrived, the show had already started.</em> (= The show started first, then he arrived.) <em>She had never visited London before.</em> <em>They had been waiting for an hour when the train finally came.</em> Use it to make the sequence of events clear and to add depth to your story.",
      },
    ],
    examples: [
      { en: "I was walking home when I suddenly heard a loud noise.", da: "Jeg gik hjem, da jeg pludselig hørte en høj lyd." },
      { en: "Everyone was having dinner when the lights went out.", da: "Alle spiste aftensmad, da lyset gik ud." },
      { en: "By the time we arrived, the train had already left.", da: "Da vi ankom, var toget allerede afgået." },
      { en: "She had never visited London before, so everything was new to her.", da: "Hun havde aldrig besøgt London før, så alt var nyt for hende." },
      { en: "The children were playing in the garden when it started to rain.", da: "Børnene legede i haven, da det begyndte at regne." },
      { en: "He opened the door and found that someone had left a package outside.", da: "Han åbnede døren og opdagede, at nogen havde efterladt en pakke udenfor." },
      { en: "While she was waiting for the bus, she met an old friend.", da: "Mens hun ventede på bussen, mødte hun en gammel ven." },
      { en: "It was a beautiful morning. The birds were singing and the sun was rising over the hills.", da: "Det var en smuk morgen. Fuglene sang, og solen stod op over bakkerne." },
    ],
    flashcards: [
      { front: "Past continuous", back: "Fortids-progressiv: was/were + -ing" },
      { front: "Past perfect", back: "Pluskvamperfektum: had + kort tillægsform" },
      { front: "While…", back: "Mens… (to samtidige handlinger)" },
      { front: "When…", back: "Da… (baggrunds- + begivenhed)" },
      { front: "Suddenly", back: "Pludselig" },
      { front: "By the time…", back: "Da… (noget var allerede sket)" },
      { front: "Had already…", back: "Havde allerede…" },
      { front: "Meanwhile", back: "I mellemtiden" },
      { front: "She had never…", back: "Hun havde aldrig…" },
      { front: "They were + -ing", back: "De var i gang med at… (baggrund)" },
    ],
    quiz: [
      { q: "'She ___ (read) when the phone rang.' (background action)", options: ["read", "was reading", "had read", "reads"], correct: 1, explain: "Past continuous (was reading) = background action interrupted by the phone." },
      { q: "'By the time I arrived, they ___.' (left before I arrived)", options: ["left", "were leaving", "had left", "leave"], correct: 2, explain: "Past perfect (had left) shows the action was completed before my arrival." },
      { q: "Past continuous is formed with:", options: ["had + past participle", "was/were + -ing", "will + -ing", "is + past participle"], correct: 1, explain: "Past continuous = was/were + verb-ing." },
      { q: "'Everyone was dancing and the music ___.' (background)", options: ["plays", "played", "was playing", "had played"], correct: 2, explain: "Past continuous (was playing) describes background atmosphere." },
      { q: "Which sentence uses the past perfect correctly?", options: ["I went home.", "I was going home.", "I had gone home before she called.", "I go home."], correct: 2, explain: "Past perfect (had gone) shows this action completed before another past action." },
    ],
  },
  "b1-if": {
    title: "Hypotheticals & Conditionals",
    icon: "🔀", level: "B1",
    theory: [
      {
        heading: "Zero Conditional — Facts and General Truths",
        body: "Structure: <strong>If + present simple, present simple.</strong> Used for facts, scientific truths, and things that are always true: <em>If you heat water to 100°C, it boils. If I eat too much sugar, I get a headache. If it rains, the ground gets wet.</em> You can also use <em>when</em> instead of <em>if</em> for the same meaning. The result is certain — not just possible.",
      },
      {
        heading: "First Conditional — Real Future Possibility",
        body: "Structure: <strong>If + present simple, will + infinitive.</strong> Used for real, possible situations in the future: <em>If it rains tomorrow, I will stay at home. If you study hard, you will pass the exam. If she calls, I'll tell her.</em> The situation is genuinely possible. You can reverse the clauses: <em>I'll stay at home if it rains.</em> (No comma when 'if' clause comes second.)",
      },
      {
        heading: "Second Conditional — Imaginary or Unlikely Situations",
        body: "Structure: <strong>If + past simple, would + infinitive.</strong> Used for imaginary, hypothetical, or unlikely situations NOW or in the future: <em>If I had more time, I would travel more. If I were you, I would apply for the job. If she won the lottery, she would buy a house.</em> Special note: use <strong>were</strong> (not <em>was</em>) after <em>I</em> in formal writing: <em>If I were a doctor…</em> This is called the 'subjunctive'.",
      },
    ],
    examples: [
      { en: "If I had more time, I would travel around the world.", da: "Hvis jeg havde mere tid, ville jeg rejse verden rundt." },
      { en: "If you study every day, you will improve your English.", da: "Hvis du studerer hver dag, vil du forbedre dit engelsk." },
      { en: "If water drops below 0°C, it freezes.", da: "Hvis vand falder under 0°C, fryser det." },
      { en: "I would buy a house in the country if I won the lottery.", da: "Jeg ville købe et hus på landet, hvis jeg vandt i lotteriet." },
      { en: "If you heat the soup, it will be ready in five minutes.", da: "Hvis du opvarmer suppen, vil den være klar om fem minutter." },
      { en: "If I were a doctor, I would work in an international health organisation.", da: "Hvis jeg var læge, ville jeg arbejde i en international sundhedsorganisation." },
      { en: "You'll miss the train if you don't hurry.", da: "Du kommer til at misse toget, hvis du ikke skynder dig." },
      { en: "What would you do if you could live anywhere in the world?", da: "Hvad ville du gøre, hvis du kunne bo et vilkårligt sted i verden?" },
    ],
    flashcards: [
      { front: "Zero conditional", back: "If + present → present (fakta)" },
      { front: "First conditional", back: "If + present → will (reel mulighed)" },
      { front: "Second conditional", back: "If + past → would (hypotetisk)" },
      { front: "I would…", back: "Jeg ville… (hypotetisk)" },
      { front: "If I were you…", back: "Hvis jeg var dig…" },
      { front: "Unless", back: "Medmindre (= if … not)" },
      { front: "Provided that", back: "Forudsat at" },
      { front: "As long as", back: "Så længe som" },
      { front: "Hypothetical", back: "Hypotetisk / forestillet" },
      { front: "Result clause", back: "Konsekvenssætning" },
    ],
    quiz: [
      { q: "'If it ___, we will cancel the picnic.' (first conditional)", options: ["rained", "rains", "would rain", "raining"], correct: 1, explain: "First conditional: If + present simple. 'If it rains' = real possibility." },
      { q: "'If I ___ a million pounds, I would buy a yacht.' (second conditional)", options: ["have", "had", "would have", "having"], correct: 1, explain: "Second conditional: If + past simple. 'If I had a million pounds' = imaginary." },
      { q: "Which is a zero conditional sentence?", options: ["If I had time, I'd go.", "If you call, I will answer.", "If you mix red and blue, you get purple.", "I would go if I could."], correct: 2, explain: "Zero conditional states a fact: mixing colours always produces the same result." },
      { q: "'I would travel more if I ___ more free time.'", options: ["have", "will have", "had", "would have"], correct: 2, explain: "Second conditional: If + past simple. 'If I had more free time' (but I don't)." },
      { q: "Second conditional describes:", options: ["a real future possibility", "a scientific fact", "an imaginary or unlikely situation", "a past habit"], correct: 2, explain: "Second conditional = hypothetical/imaginary situations in the present or future." },
    ],
  },
  "b1-news": {
    title: "News, Media & Reported Speech",
    icon: "📰", level: "B1",
    theory: [
      {
        heading: "News and Media Vocabulary",
        body: "Types of media: <strong>newspaper, magazine, online news, TV / broadcast news, podcast, social media, radio.</strong> People: <strong>journalist, reporter, editor, correspondent, presenter / anchor.</strong> Story types: <strong>headline</strong> (title of a story), <strong>article, report, editorial</strong> (opinion piece), <strong>breaking news</strong> (important news happening right now), <strong>interview, feature.</strong> To describe sources: <strong>according to [source], sources say that…</strong>",
      },
      {
        heading: "Reported Speech: Statements",
        body: "When reporting what someone said, shift the tenses back (called 'backshift'): <strong>Present → Past:</strong> <em>'I am happy.' → She said she was happy.</em> <strong>Past → Past perfect:</strong> <em>'I went.' → He said he had gone.</em> <strong>Will → Would:</strong> <em>'I will help.' → She said she would help.</em> <strong>Can → Could:</strong> <em>'I can come.' → He said he could come.</em> Also change pronouns and time expressions: <em>'I'll call you tomorrow' → She said she would call me the next day.</em>",
      },
      {
        heading: "Reported Speech: Questions",
        body: "For reported questions, use <strong>normal word order</strong> (subject + verb), NOT the inverted question order. <strong>Wh-questions:</strong> <em>'Where do you live?' → She asked where I lived.</em> <strong>Yes/No questions:</strong> use <strong>if / whether</strong>: <em>'Are you coming?' → He asked if/whether I was coming.</em> Note: do NOT use 'do/does/did' in reported questions: ✗ <em>She asked where did I live.</em> ✓ <em>She asked where I lived.</em>",
      },
    ],
    examples: [
      { en: "She told me that the meeting had been cancelled.", da: "Hun fortalte mig, at mødet var blevet aflyst." },
      { en: "The journalist reported that the election results were being counted.", da: "Journalisten rapporterede, at valgresultaterne var ved at blive optalt." },
      { en: "He asked me where I was going.", da: "Han spurgte mig, hvor jeg var på vej hen." },
      { en: "The newspaper said that prices would rise next year.", da: "Avisen sagde, at priserne ville stige næste år." },
      { en: "She asked whether I had seen the news that morning.", da: "Hun spurgte, om jeg havde set nyhederne den morgen." },
      { en: "Breaking news reported that a major earthquake had hit the region.", da: "Breaking news rapporterede, at et kraftigt jordskælv havde ramt regionen." },
      { en: "The prime minister told reporters that the economy was improving.", da: "Statsministeren fortalte journalister, at økonomien var ved at forbedre sig." },
      { en: "He announced that he had decided to resign from his position.", da: "Han meddelte, at han havde besluttet at træde tilbage fra sin stilling." },
    ],
    flashcards: [
      { front: "Headline", back: "Overskrift (i avis/nyhed)" },
      { front: "Breaking news", back: "Seneste nyt / Eilmeldung" },
      { front: "According to…", back: "Ifølge…" },
      { front: "She said (that)…", back: "Hun sagde, at…" },
      { front: "He asked if/whether…", back: "Han spurgte, om…" },
      { front: "Tense backshift", back: "Tidsforskydning i refereret tale" },
      { front: "She asked where I lived.", back: "Normal ordstilling i indirekte spørgsmål" },
      { front: "Would (reported will)", back: "Ville (fremtid i refereret tale)" },
      { front: "The next day", back: "Dagen efter (skift fra 'tomorrow')" },
      { front: "Correspondent", back: "Korrespondent (journalist)" },
    ],
    quiz: [
      { q: "Direct: 'I am tired.' → Reported: 'She said she ___ tired.'", options: ["is", "was", "were", "has been"], correct: 1, explain: "Present simple → past simple in reported speech: 'am' → 'was'." },
      { q: "Direct: 'I will call you.' → Reported: 'He said he ___ call me.'", options: ["will", "would", "shall", "can"], correct: 1, explain: "'Will' → 'would' in reported speech." },
      { q: "Reported question: 'Where do you live?' → 'She asked where I ___.'", options: ["live", "lived", "do live", "did live"], correct: 1, explain: "Reported questions use past tense and normal word order (no 'do'): 'where I lived'." },
      { q: "'Breaking news' means:", options: ["old, archived stories", "important news happening right now", "entertainment news", "opinion articles"], correct: 1, explain: "Breaking news = important events happening right now or very recently." },
      { q: "Which is correct reported speech for 'Are you coming?'", options: ["He asked was I coming.", "He asked if I was coming.", "He asked if was I coming.", "He asked am I coming."], correct: 1, explain: "Yes/No reported questions use 'if/whether' + subject + verb (no inversion)." },
    ],
  },
  "b1-email": {
    title: "Emails & Formal Language",
    icon: "✉️", level: "B1",
    theory: [
      {
        heading: "Formal Email Structure",
        body: "<strong>Opening:</strong> <em>Dear Mr/Ms [Surname],</em> (if you know the name) or <em>Dear Sir/Madam,</em> (if you don't know). Do not use first names in formal emails unless invited to. <strong>First line:</strong> State your purpose clearly: <em>I am writing to enquire about… / I am writing with reference to… / Further to our conversation…</em> <strong>Body:</strong> Give details, make requests. <strong>Closing:</strong> <em>I look forward to hearing from you. / Please do not hesitate to contact me.</em> <strong>Sign-off:</strong> <em>Yours sincerely,</em> (when you know the name) or <em>Yours faithfully,</em> (Dear Sir/Madam). Then your full name.",
      },
      {
        heading: "Formal Language Features",
        body: "In formal emails: <strong>Use full forms</strong> (not contractions): write <em>I am</em> not <em>I'm</em>, <em>I would</em> not <em>I'd</em>. <strong>Choose formal vocabulary:</strong> <em>enquire</em> (not <em>ask</em>), <em>commence</em> (not <em>start</em>), <em>require</em> (not <em>need</em>), <em>assist</em> (not <em>help</em>), <em>inform</em> (not <em>tell</em>), <em>receive</em> (not <em>get</em>), <em>request</em> (not <em>ask for</em>). <strong>Be indirect and polite:</strong> <em>I would be grateful if you could…</em> is much more polite than <em>Please send me…</em>",
      },
      {
        heading: "Key Phrases for Formal Emails",
        body: "<strong>Opening purpose:</strong> <em>I am writing to enquire about… / I am writing to complain about… / I am writing to apply for… / I am writing to confirm…</em> <strong>Requests:</strong> <em>I would be grateful if you could… / Could you please… / I would appreciate it if…</em> <strong>Attachments:</strong> <em>Please find attached… / I am attaching…</em> <strong>Apologies:</strong> <em>I am afraid I will be unable to… / I am sorry to inform you that…</em> <strong>Closing:</strong> <em>I look forward to hearing from you. / I look forward to your reply. / Please do not hesitate to contact me if you require further information.</em>",
      },
    ],
    examples: [
      { en: "I am writing to enquire about the position advertised online.", da: "Jeg skriver for at forhøre mig om stillingen annonceret online." },
      { en: "I would be grateful if you could send me further information.", da: "Jeg ville være taknemmelig, hvis du kunne sende mig yderligere oplysninger." },
      { en: "Dear Mr Jensen, Thank you for your email of the 15th of March.", da: "Kære hr. Jensen, tak for din e-mail af den 15. marts." },
      { en: "I look forward to hearing from you at your earliest convenience.", da: "Jeg ser frem til at høre fra dig ved din tidligste lejlighed." },
      { en: "Please find attached my CV and cover letter as requested.", da: "Se venligst det vedhæftede CV og ansøgning som ønsket." },
      { en: "Further to our telephone conversation, I am writing to confirm the details.", da: "Med reference til vores telefonsamtale skriver jeg for at bekræfte detaljerne." },
      { en: "I am afraid I will be unable to attend the meeting on Thursday.", da: "Jeg er bange for, at jeg ikke vil være i stand til at deltage i mødet torsdag." },
      { en: "Should you require any further information, please do not hesitate to contact me.", da: "Hvis du har brug for yderligere oplysninger, er du velkommen til at kontakte mig." },
    ],
    flashcards: [
      { front: "Dear Mr/Ms…", back: "Kære hr./fru… (kendt modtager)" },
      { front: "Dear Sir/Madam", back: "Kære hr./fru (ukendt modtager)" },
      { front: "I am writing to…", back: "Jeg skriver for at…" },
      { front: "I would be grateful if…", back: "Jeg ville være taknemmelig, hvis…" },
      { front: "Please find attached", back: "Se venligst vedhæftede" },
      { front: "I look forward to…", back: "Jeg ser frem til…" },
      { front: "Yours sincerely", back: "Med venlig hilsen (kender navn)" },
      { front: "Yours faithfully", back: "Med venlig hilsen (kender ikke navn)" },
      { front: "I am afraid…", back: "Jeg er bange for, at… (formelt undskyld)" },
      { front: "Enquire", back: "Forhøre sig (formelt for 'ask')" },
    ],
    quiz: [
      { q: "You know the recipient's name (you wrote 'Dear Mr Brown'). The sign-off is:", options: ["Yours faithfully,", "Yours sincerely,", "Best wishes,", "Cheers,"], correct: 1, explain: "Rule: Dear + name → Yours sincerely. Dear Sir/Madam → Yours faithfully." },
      { q: "Formal version of 'I want to ask about the job':", options: ["I wanna know about the job.", "I am writing to enquire about the position.", "Can you tell me about the job?", "What about the job?"], correct: 1, explain: "'I am writing to enquire about the position' is formal and professional." },
      { q: "'Please find attached' means:", options: ["please send an attachment", "I have attached a document", "please find the office", "look for the file"], correct: 1, explain: "'Please find attached' tells the reader you have included a document with the email." },
      { q: "Which is NOT appropriate in a formal email?", options: ["I am writing to confirm…", "I'd just like to check something quickly…", "I would be grateful if you could…", "Further to our conversation…"], correct: 1, explain: "Contractions ('I'd') and informal phrases are not appropriate in formal emails." },
      { q: "Which closing phrase is correct for a formal email?", options: ["See ya!", "Take care!", "I look forward to hearing from you.", "Speak soon!"], correct: 2, explain: "'I look forward to hearing from you' is the standard formal email closing." },
    ],
  },
  "b1-feel": {
    title: "Feelings & Experiences",
    icon: "🎭", level: "B1",
    theory: [
      {
        heading: "Vocabulary for Feelings",
        body: "Basic emotions: <strong>happy, sad, angry, scared / frightened, surprised, excited, nervous / anxious, bored, tired, proud, embarrassed, disappointed, jealous, grateful, frustrated, confused, relieved, lonely, content.</strong> More nuanced: <em>melancholy</em> (sad), <em>elated</em> (very happy), <em>apprehensive</em> (worried about the future), <em>overwhelmed</em> (too much to handle), <em>nostalgic</em> (fond memories of the past).",
      },
      {
        heading: "Present Perfect for Life Experiences",
        body: "Use the <strong>present perfect (have/has + past participle)</strong> to talk about life experiences without saying when: <em>Have you ever been to Japan? I have never tried sushi. She has visited over 20 countries. He has won several awards.</em> With specific time → use past simple: <em>I went to Japan in 2018.</em> Key words with present perfect experiences: <strong>ever</strong> (in questions), <strong>never</strong> (negative), <strong>already</strong> (sooner than expected), <strong>yet</strong> (not happened so far).",
      },
      {
        heading: "Gradable and Non-gradable Adjectives",
        body: "<strong>Gradable adjectives</strong> have different degrees and use <em>very / really</em>: <em>very tired, really happy, quite cold.</em> <strong>Non-gradable (extreme) adjectives</strong> already contain the idea of 'very' and use <em>absolutely</em>: <em>absolutely exhausted</em> (not 'very exhausted'), <em>absolutely delighted, absolutely terrified, absolutely furious, absolutely freezing.</em> Common pairs: scared → terrified, happy → delighted, tired → exhausted, angry → furious, hungry → starving, cold → freezing.",
      },
    ],
    examples: [
      { en: "I have been living in Copenhagen for three years.", da: "Jeg har boet i København i tre år." },
      { en: "Have you ever tried traditional British food like a Sunday roast?", da: "Har du nogensinde prøvet traditionel britisk mad som en Sunday roast?" },
      { en: "She was absolutely delighted when she heard the news.", da: "Hun var fuldstændig henrykt, da hun hørte nyhederne." },
      { en: "I have never felt so nervous in my life as before that exam.", da: "Jeg har aldrig følt mig så nervøs i mit liv som inden den eksamen." },
      { en: "He feels very frustrated when he can't communicate his ideas clearly.", da: "Han føler sig meget frustreret, når han ikke kan kommunikere sine ideer tydeligt." },
      { en: "I'm really excited about my trip to Scotland next month.", da: "Jeg er virkelig begejstret for min tur til Skotland næste måned." },
      { en: "We were absolutely exhausted after hiking for eight hours in the mountains.", da: "Vi var fuldstændig udmattede efter at have vandret i otte timer i bjergene." },
      { en: "She has won the award for best teacher three years in a row.", da: "Hun har vundet prisen for bedste lærer tre år i træk." },
    ],
    flashcards: [
      { front: "Excited", back: "Begejstret / Spændt" },
      { front: "Nervous / Anxious", back: "Nervøs / Urolig" },
      { front: "Proud", back: "Stolt" },
      { front: "Embarrassed", back: "Flov / Forlegen" },
      { front: "Relieved", back: "Lettet" },
      { front: "Absolutely delighted", back: "Fuldstændig henrykt" },
      { front: "Absolutely exhausted", back: "Fuldstændig udmattet" },
      { front: "Have you ever…?", back: "Har du nogensinde…?" },
      { front: "I have never…", back: "Jeg har aldrig…" },
      { front: "Three years in a row", back: "Tre år i træk" },
    ],
    quiz: [
      { q: "'Have you ever ___ to Scotland?' (experience question)", options: ["been", "went", "go", "gone"], correct: 0, explain: "'Have you ever been to…?' is the standard expression for asking about life experiences. 'Been' is the past participle of 'be/go' used with 'have you ever'." },
      { q: "'She is absolutely ___.' (she cannot move, she is so tired)", options: ["very tired", "exhausted", "tired", "sleepy"], correct: 1, explain: "'Absolutely exhausted' is the extreme adjective. Never say 'absolutely tired' or 'very exhausted'." },
      { q: "Present perfect for experiences: 'I ___ never tried caviar.'", options: ["have", "had", "did", "am"], correct: 0, explain: "Present perfect = have/has + past participle. 'I have never tried' is correct." },
      { q: "'I was absolutely terrified' expresses:", options: ["mild fear", "happiness", "extreme fear", "surprise"], correct: 2, explain: "'Terrified' is the extreme/non-gradable form of 'scared'. 'Absolutely terrified' = extremely scared." },
      { q: "'She has visited 15 countries.' This tells us:", options: ["exactly when she visited each country", "her life experience so far", "where she is right now", "her plans for the future"], correct: 1, explain: "Present perfect (has visited) talks about life experience without specifying exact times." },
    ],
  },
};
